// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Sep 2017 19:48:57 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "ogg/ogg.h"
#include "vorbis/codec.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

