// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 01 May 2019 16:47:00 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package vorbis

/*
#cgo pkg-config: ogg vorbis vorbisenc
#include "ogg/ogg.h"
#include "vorbis/codec.h"
#include "vorbis/vorbisenc.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// OvFalse as defined in xlab/vorbis-go:0
	OvFalse = -1
	// OvEof as defined in xlab/vorbis-go:0
	OvEof = -2
	// OvHole as defined in xlab/vorbis-go:0
	OvHole = -3
	// OvEread as defined in xlab/vorbis-go:0
	OvEread = -128
	// OvEfault as defined in xlab/vorbis-go:0
	OvEfault = -129
	// OvEimpl as defined in xlab/vorbis-go:0
	OvEimpl = -130
	// OvEinval as defined in xlab/vorbis-go:0
	OvEinval = -131
	// OvEnotvorbis as defined in xlab/vorbis-go:0
	OvEnotvorbis = -132
	// OvEbadheader as defined in xlab/vorbis-go:0
	OvEbadheader = -133
	// OvEversion as defined in xlab/vorbis-go:0
	OvEversion = -134
	// OvEnotaudio as defined in xlab/vorbis-go:0
	OvEnotaudio = -135
	// OvEbadpacket as defined in xlab/vorbis-go:0
	OvEbadpacket = -136
	// OvEbadlink as defined in xlab/vorbis-go:0
	OvEbadlink = -137
	// OvEnoseek as defined in xlab/vorbis-go:0
	OvEnoseek = -138
	// OvEctlRatemanage2Get as defined in xlab/vorbis-go:0
	OvEctlRatemanage2Get = 20
	// OvEctlRatemanage2Set as defined in xlab/vorbis-go:0
	OvEctlRatemanage2Set = 21
	// OvEctlLowpassGet as defined in xlab/vorbis-go:0
	OvEctlLowpassGet = 32
	// OvEctlLowpassSet as defined in xlab/vorbis-go:0
	OvEctlLowpassSet = 33
	// OvEctlIblockGet as defined in xlab/vorbis-go:0
	OvEctlIblockGet = 48
	// OvEctlIblockSet as defined in xlab/vorbis-go:0
	OvEctlIblockSet = 49
	// OvEctlCouplingGet as defined in xlab/vorbis-go:0
	OvEctlCouplingGet = 64
	// OvEctlCouplingSet as defined in xlab/vorbis-go:0
	OvEctlCouplingSet = 65
	// OvEctlRatemanageGet as defined in xlab/vorbis-go:0
	OvEctlRatemanageGet = 16
	// OvEctlRatemanageSet as defined in xlab/vorbis-go:0
	OvEctlRatemanageSet = 17
	// OvEctlRatemanageAvg as defined in xlab/vorbis-go:0
	OvEctlRatemanageAvg = 18
	// OvEctlRatemanageHard as defined in xlab/vorbis-go:0
	OvEctlRatemanageHard = 19
)
