// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 19 Jan 2019 16:37:10 GMT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package vorbis

/*
#cgo pkg-config: ogg vorbis
#include "ogg/ogg.h"
#include "vorbis/codec.h"
#include "vorbis/vorbisenc.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// OvFalse as defined in vorbis/codec.h:222
	OvFalse = -1
	// OvEof as defined in vorbis/codec.h:223
	OvEof = -2
	// OvHole as defined in vorbis/codec.h:224
	OvHole = -3
	// OvEread as defined in vorbis/codec.h:226
	OvEread = -128
	// OvEfault as defined in vorbis/codec.h:227
	OvEfault = -129
	// OvEimpl as defined in vorbis/codec.h:228
	OvEimpl = -130
	// OvEinval as defined in vorbis/codec.h:229
	OvEinval = -131
	// OvEnotvorbis as defined in vorbis/codec.h:230
	OvEnotvorbis = -132
	// OvEbadheader as defined in vorbis/codec.h:231
	OvEbadheader = -133
	// OvEversion as defined in vorbis/codec.h:232
	OvEversion = -134
	// OvEnotaudio as defined in vorbis/codec.h:233
	OvEnotaudio = -135
	// OvEbadpacket as defined in vorbis/codec.h:234
	OvEbadpacket = -136
	// OvEbadlink as defined in vorbis/codec.h:235
	OvEbadlink = -137
	// OvEnoseek as defined in vorbis/codec.h:236
	OvEnoseek = -138
	// OvEctlRatemanage2Get as defined in vorbis/vorbisenc.h:313
	OvEctlRatemanage2Get = 20
	// OvEctlRatemanage2Set as defined in vorbis/vorbisenc.h:324
	OvEctlRatemanage2Set = 21
	// OvEctlLowpassGet as defined in vorbis/vorbisenc.h:332
	OvEctlLowpassGet = 32
	// OvEctlLowpassSet as defined in vorbis/vorbisenc.h:340
	OvEctlLowpassSet = 33
	// OvEctlIblockGet as defined in vorbis/vorbisenc.h:348
	OvEctlIblockGet = 48
	// OvEctlIblockSet as defined in vorbis/vorbisenc.h:359
	OvEctlIblockSet = 49
	// OvEctlCouplingGet as defined in vorbis/vorbisenc.h:367
	OvEctlCouplingGet = 64
	// OvEctlCouplingSet as defined in vorbis/vorbisenc.h:379
	OvEctlCouplingSet = 65
	// OvEctlRatemanageGet as defined in vorbis/vorbisenc.h:393
	OvEctlRatemanageGet = 16
	// OvEctlRatemanageSet as defined in vorbis/vorbisenc.h:404
	OvEctlRatemanageSet = 17
	// OvEctlRatemanageAvg as defined in vorbis/vorbisenc.h:415
	OvEctlRatemanageAvg = 18
	// OvEctlRatemanageHard as defined in vorbis/vorbisenc.h:426
	OvEctlRatemanageHard = 19
)
