// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 05 Mar 2016 02:56:32 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package vorbis provides Go bindings for OggVorbis implementation by the Xiph.Org Foundation
*/
package vorbis
