// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 24 Jan 2019 20:42:41 GMT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vorbis provides Go bindings for OggVorbis implementation by the Xiph.Org Foundation
*/
package vorbis
