// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 27 Sep 2016 22:07:58 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package vorbis provides Go bindings for OggVorbis implementation by the Xiph.Org Foundation
*/
package vorbis
